// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedS31u3QF7GJX7Tc6z20hLmnrj-wLs9k',
    appId: '1:787119170758:web:02ae09d7686811e0ea23c7',
    messagingSenderId: '787119170758',
    projectId: 'gaorre-97b39',
    authDomain: 'gaorre-97b39.firebaseapp.com',
    storageBucket: 'gaorre-97b39.appspot.com',
    measurementId: 'G-Y6XX6NJ8LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluXqBRmdI00pVU5SENLgF2WnLVlO-bds',
    appId: '1:787119170758:android:17f95cbb6bdc4e0eea23c7',
    messagingSenderId: '787119170758',
    projectId: 'gaorre-97b39',
    storageBucket: 'gaorre-97b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7T4N2QrsUGLDbpAT-xC4zT1I2sQzT48c',
    appId: '1:787119170758:ios:444648ed1fcc5e9dea23c7',
    messagingSenderId: '787119170758',
    projectId: 'gaorre-97b39',
    storageBucket: 'gaorre-97b39.appspot.com',
    iosBundleId: 'com.aeioudev.gaorre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7T4N2QrsUGLDbpAT-xC4zT1I2sQzT48c',
    appId: '1:787119170758:ios:d3755c3a7587c9e0ea23c7',
    messagingSenderId: '787119170758',
    projectId: 'gaorre-97b39',
    storageBucket: 'gaorre-97b39.appspot.com',
    iosBundleId: 'com.example.orreManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBedS31u3QF7GJX7Tc6z20hLmnrj-wLs9k',
    appId: '1:787119170758:web:55ef4537e7f07237ea23c7',
    messagingSenderId: '787119170758',
    projectId: 'gaorre-97b39',
    authDomain: 'gaorre-97b39.firebaseapp.com',
    storageBucket: 'gaorre-97b39.appspot.com',
    measurementId: 'G-0V53NL6ML7',
  );
}
